"""auto

Revision ID: 668b9d7961e7
Revises: 
Create Date: 2020-12-17 19:06:47.591828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668b9d7961e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('aprice', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('astatus', sa.Boolean(), nullable=True),
    sa.Column('img_url', sa.String(length=128), nullable=True),
    sa.Column('img_url2', sa.String(length=128), nullable=True),
    sa.Column('img_url3', sa.String(length=128), nullable=True),
    sa.Column('img_url4', sa.String(length=128), nullable=True),
    sa.Column('rented', sa.DateTime(), nullable=True),
    sa.Column('end_of_rent', sa.DateTime(), nullable=True),
    sa.Column('arented', sa.DateTime(), nullable=True),
    sa.Column('aend_of_rent', sa.DateTime(), nullable=True),
    sa.Column('aurented', sa.DateTime(), nullable=True),
    sa.Column('auend_of_rent', sa.DateTime(), nullable=True),
    sa.Column('auprice', sa.Float(asdecimal=True), nullable=True),
    sa.Column('autprice', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('total_time', sa.DateTime(), nullable=True),
    sa.Column('atotal_time', sa.Integer(), nullable=True),
    sa.Column('rent_count', sa.Integer(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('img_url_2', sa.String(length=128), nullable=True),
    sa.Column('img_url_3', sa.String(length=128), nullable=True),
    sa.Column('img_url_4', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rentlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('rented', sa.DateTime(), nullable=True),
    sa.Column('end_of_rent', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('rentprice', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentlog')
    op.drop_table('auto')
    # ### end Alembic commands ###
